repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
  -  id: check-yaml
  -  id: end-of-file-fixer
  -  id: trailing-whitespace
  -  id: check-shebang-scripts-are-executable

- repo: https://github.com/FreeAndFair/commitlint-pre-commit-hook
  rev: v9.22.0
  hooks:
      - id: commitlint
        stages: [commit-msg]
        additional_dependencies: ['@commitlint/config-conventional']

- repo: https://github.com/FreeAndFair/pre-commit-rust
  rev: v1.2.1
  hooks:
      - id: fmt
        args: ['--all', '--manifest-path', 'implementations/rust/workspace/Cargo.toml', '--', '--style-edition', '2024']
      - id: cargo-check
        args: ['--manifest-path', 'implementations/rust/workspace/Cargo.toml']
      - id: clippy
        args: ['--manifest-path', 'implementations/rust/workspace/Cargo.toml', '--', '-D', 'warnings']
