
# cargo-vet config file

[cargo-vet]
version = "0.10"

[imports.google]
url = "https://raw.githubusercontent.com/google/supply-chain/main/audits.toml"

[imports.zcash]
url = "https://raw.githubusercontent.com/zcash/rust-ecosystem/main/supply-chain/audits.toml"

[[exemptions.base16ct]]
version = "0.2.0"
criteria = "safe-to-deploy"

[[exemptions.base64ct]]
version = "1.8.0"
criteria = "safe-to-deploy"

[[exemptions.bincode]]
version = "2.0.1"
criteria = "safe-to-run"

[[exemptions.bincode_derive]]
version = "2.0.1"
criteria = "safe-to-run"

[[exemptions.block-buffer]]
version = "0.10.4"
criteria = "safe-to-deploy"

[[exemptions.cfg-if]]
version = "1.0.3"
criteria = "safe-to-deploy"

[[exemptions.const-oid]]
version = "0.9.6"
criteria = "safe-to-deploy"

[[exemptions.cpufeatures]]
version = "0.2.17"
criteria = "safe-to-deploy"

[[exemptions.crossbeam-deque]]
version = "0.8.6"
criteria = "safe-to-deploy"

[[exemptions.crossbeam-epoch]]
version = "0.9.18"
criteria = "safe-to-deploy"

[[exemptions.crossbeam-utils]]
version = "0.8.21"
criteria = "safe-to-deploy"

[[exemptions.crypto-bigint]]
version = "0.5.5"
criteria = "safe-to-deploy"

[[exemptions.crypto-common]]
version = "0.1.6"
criteria = "safe-to-deploy"

[[exemptions.curve25519-dalek]]
version = "4.1.3"
criteria = "safe-to-deploy"

[[exemptions.curve25519-dalek-derive]]
version = "0.1.1"
criteria = "safe-to-deploy"

[[exemptions.der]]
version = "0.7.10"
criteria = "safe-to-deploy"

[[exemptions.digest]]
version = "0.10.7"
criteria = "safe-to-deploy"

[[exemptions.ecdsa]]
version = "0.16.9"
criteria = "safe-to-deploy"

[[exemptions.ed25519]]
version = "2.2.3"
criteria = "safe-to-deploy"

[[exemptions.ed25519-dalek]]
version = "2.2.0"
criteria = "safe-to-deploy"

[[exemptions.elliptic-curve]]
version = "0.13.8"
criteria = "safe-to-deploy"

[[exemptions.ff]]
version = "0.13.1"
criteria = "safe-to-deploy"

[[exemptions.fiat-crypto]]
version = "0.2.9"
criteria = "safe-to-deploy"

[[exemptions.generic-array]]
version = "0.14.7"
criteria = "safe-to-deploy"

[[exemptions.getrandom]]
version = "0.2.16"
criteria = "safe-to-deploy"

[[exemptions.group]]
version = "0.13.0"
criteria = "safe-to-deploy"

[[exemptions.hex]]
version = "0.4.3"
criteria = "safe-to-deploy"

[[exemptions.hmac]]
version = "0.12.1"
criteria = "safe-to-deploy"

[[exemptions.keccak]]
version = "0.1.5"
criteria = "safe-to-deploy"

[[exemptions.libc]]
version = "0.2.175"
criteria = "safe-to-deploy"

[[exemptions.p256]]
version = "0.13.2"
criteria = "safe-to-deploy"

[[exemptions.pem-rfc7468]]
version = "0.7.0"
criteria = "safe-to-deploy"

[[exemptions.pkcs8]]
version = "0.10.2"
criteria = "safe-to-deploy"

[[exemptions.ppv-lite86]]
version = "0.2.21"
criteria = "safe-to-deploy"

[[exemptions.primeorder]]
version = "0.13.6"
criteria = "safe-to-deploy"

[[exemptions.proc-macro2]]
version = "1.0.101"
criteria = "safe-to-deploy"

[[exemptions.rayon]]
version = "1.11.0"
criteria = "safe-to-deploy"

[[exemptions.rayon-core]]
version = "1.13.0"
criteria = "safe-to-deploy"

[[exemptions.rfc6979]]
version = "0.4.0"
criteria = "safe-to-deploy"

[[exemptions.sec1]]
version = "0.7.3"
criteria = "safe-to-deploy"

[[exemptions.semver]]
version = "1.0.26"
criteria = "safe-to-deploy"

[[exemptions.sha2]]
version = "0.10.9"
criteria = "safe-to-deploy"

[[exemptions.sha3]]
version = "0.10.8"
criteria = "safe-to-deploy"

[[exemptions.spki]]
version = "0.7.3"
criteria = "safe-to-deploy"

[[exemptions.subtle]]
version = "2.6.1"
criteria = "safe-to-deploy"

[[exemptions.syn]]
version = "2.0.106"
criteria = "safe-to-deploy"

[[exemptions.thiserror]]
version = "1.0.69"
criteria = "safe-to-deploy"

[[exemptions.thiserror-impl]]
version = "1.0.69"
criteria = "safe-to-deploy"

[[exemptions.typenum]]
version = "1.18.0"
criteria = "safe-to-deploy"

[[exemptions.unicode-ident]]
version = "1.0.19"
criteria = "safe-to-deploy"

[[exemptions.unty]]
version = "0.0.4"
criteria = "safe-to-run"

[[exemptions.version_check]]
version = "0.9.5"
criteria = "safe-to-deploy"

[[exemptions.virtue]]
version = "0.0.18"
criteria = "safe-to-run"

[[exemptions.wasi]]
version = "0.11.1+wasi-snapshot-preview1"
criteria = "safe-to-deploy"

[[exemptions.zerocopy]]
version = "0.8.27"
criteria = "safe-to-deploy"

[[exemptions.zerocopy-derive]]
version = "0.8.27"
criteria = "safe-to-deploy"

[[exemptions.zeroize]]
version = "1.8.1"
criteria = "safe-to-deploy"
