[workspace]
members = ["crypto"]
resolver = "2"

[workspace.package]
authors = ["Your Name <your.email@example.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/your-org/your-repo"

[workspace.dependencies]
