[package]
name = "sr"
version = "0.1.0"
edition = "2024"

[dependencies]
ascent = "0.8.0"
stateright = "0.31.0"
rand = "0.8"
strum = { version = "0.27", features = ["derive"] }
hex = "0.4.3"
thread_local = "1.1.9"

crypto = { path = "../../mono/crypto" }
