# .github/workflows/run-makefile-for-clafer-model.yml
# Author: Daniel M. Zimmerman
# Created: 2025-02-24
# Modified: 2025-02-24

name: Run pre-commit Hooks

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  pre-commit:
    name: Run pre-commit Hooks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - uses: pre-commit/action@v3.0.1
