# .github/workflows/run-precommit-hooks.yml
# Author: Daniel M. Zimmerman
# Created: 2025-02-24
# Modified: 2025-09-03

name: Run pre-commit Hooks

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  pre-commit:
    name: Run pre-commit Hooks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Switch to Nightly Rust
        run: |
          rustup toolchain install nightly
          rustup default nightly
          rustup component add rustfmt clippy
          rustup --version

      - name: Set Up Python
        uses: actions/setup-python@v3

      - name: Run Pre-Commit Hooks
        uses: pre-commit/action@v3.0.1
