# .github/workflows/test-validity-of-refinements-paper.yml
# Author: Daniel M. Zimmerman
# Created: 2025-02-20
# Modified: 2025-03-15

# This workflow tests the validity of the "Refinements Among
# High Level Models" paper by building it. It also saves the
# resulting artifact.

name: Test Validity of "Refinements Among High-Level Models" Paper

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
    paths:
      - 'docs/papers/refinements_among_high_level_models/**'

  workflow_dispatch:

jobs:
  refinements-paper:
    name: Run Latexmk on Paper
    runs-on: ubuntu-latest
    steps:
      - name: Install/Restore TeXLive Environment
        uses: FreeAndFair/setup-texlive-action@v3
        with:
          packages: |
            scheme-full

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run Latexmk in Paper Directory
        run: |
          cd docs/papers/refinements_among_high_level_models
          latexmk --pdf refinements_paper.tex

      - name: Save the Generated PDF
        uses: actions/upload-artifact@v4
        with:
          name: refinements_among_high_level_models_paper
          path: docs/papers/refinements_among_high_level_models/refinements_paper.pdf
